local tar local submodules

diff --git a/make-dist b/make-dist
--- a/make-dist
+++ b/make-dist
@@ -1,5 +1,7 @@
 #!/bin/bash -e
 
+source offline-build.sh
+
 SCRIPTNAME="$(basename "${0}")"
 BASEDIR="$(readlink -f "$(dirname "${0}")")"
 
@@ -33,12 +35,16 @@ outfile="ceph-$version"
 echo "version $version"
 
 # update submodules
-echo "updating submodules..."
-force=$(if git submodule usage 2>&1 | grep --quiet 'update.*--force'; then echo --force ; fi)
-if ! git submodule sync || ! git submodule update $force --init --recursive; then
-    echo "Error: could not initialize submodule projects"
-    echo "  Network connectivity might be required."
-    exit 1
+if [ $OFFLINE_BUIlD ]; then
+  echo "Offline build, skip submodules update..."
+else
+  echo "updating submodules..."
+  force=$(if git submodule usage 2>&1 | grep --quiet 'update.*--force'; then echo --force ; fi)
+  if ! git submodule sync || ! git submodule update $force --init --recursive; then
+      echo "Error: could not initialize submodule projects"
+      echo "  Network connectivity might be required."
+      exit 1
+  fi
 fi
 
 download_from() {
@@ -127,30 +133,56 @@ download_pmdk() {
 }
 
 build_dashboard_frontend() {
-  CURR_DIR=`pwd`
   TEMP_DIR=`mktemp -d`
+  CURR_DIR=`pwd`
 
-  $CURR_DIR/src/tools/setup-virtualenv.sh $TEMP_DIR
-  $TEMP_DIR/bin/pip install nodeenv
-  $TEMP_DIR/bin/nodeenv --verbose -p --node=12.18.2
-  cd src/pybind/mgr/dashboard/frontend
-
-  . $TEMP_DIR/bin/activate
-  npm config set registry  https://registry.npmmirror.com
-  NG_CLI_ANALYTICS=false timeout 1h npm ci
-  echo "Building ceph-dashboard frontend with build:localize script";
-  # we need to use "--" because so that "--prod" survives accross all
-  # scripts redirections inside package.json
-  npm run build:localize -- --prod
-  deactivate
-  cd $CURR_DIR
-  rm -rf $TEMP_DIR
-  tar cf dashboard_frontend.tar $outfile/src/pybind/mgr/dashboard/frontend/dist
+  if [ $OFFLINE_BUIlD ]; then
+    pushd $CURR_DIR
+    cd $TEMP_DIR
+    wget -c ${LOCAL_FILE_SERVER}/dashboard_frontend.tar
+    tar -xf dashboard_frontend.tar
+    rm -rf dashboard_frontend.tar
+    old_prefix=$(ls | grep ceph)
+    tar --transform "s/^${old_prefix}/${outfile}/" -cf $CURR_DIR/dashboard_frontend.tar $old_prefix
+    popd
+    rm -rf $TEMP_DIR
+  else
+    $CURR_DIR/src/tools/setup-virtualenv.sh $TEMP_DIR
+    $TEMP_DIR/bin/pip install nodeenv
+    $TEMP_DIR/bin/nodeenv --verbose -p --node=12.18.2
+    cd src/pybind/mgr/dashboard/frontend
+ 
+    . $TEMP_DIR/bin/activate
+    npm config set registry  https://registry.npmmirror.com
+    NG_CLI_ANALYTICS=false timeout 1h npm ci
+    echo "Building ceph-dashboard frontend with build:localize script";
+    # we need to use "--" because so that "--prod" survives accross all
+    # scripts redirections inside package.json
+    npm run build:localize -- --prod
+    deactivate
+    cd $CURR_DIR
+    rm -rf $TEMP_DIR
+    tar cf dashboard_frontend.tar $outfile/src/pybind/mgr/dashboard/frontend/dist
+  fi
 }
 
 generate_rook_ceph_client() {
-  $outfile/src/pybind/mgr/rook/generate_rook_ceph_client.sh
-  tar cf rook_ceph_client.tar $outfile/src/pybind/mgr/rook/rook_client/*.py
+  if [ $OFFLINE_BUIlD ]; then
+    TEMP_DIR=`mktemp -d`
+    CURR_DIR=`pwd`
+    pushd $CURR_DIR
+    cd $TEMP_DIR
+    wget -c ${LOCAL_FILE_SERVER}/rook_ceph_client.tar
+    tar -xf rook_ceph_client.tar
+    rm -rf rook_ceph_client.tar
+    old_prefix=$(ls | grep ceph)
+    tar --transform "s/^${old_prefix}/${outfile}/" -cf $CURR_DIR/rook_ceph_client.tar $old_prefix
+    popd
+    rm -rf $TEMP_DIR
+  else
+    $outfile/src/pybind/mgr/rook/generate_rook_ceph_client.sh
+    tar cf rook_ceph_client.tar $outfile/src/pybind/mgr/rook/rook_client/*.py
+  fi
 }
 
 # clean out old cruft...
@@ -159,7 +191,7 @@ rm -f $outfile*
 
 # build new tarball
 echo "building tarball..."
-bin/git-archive-all.sh --prefix ceph-$version/ \
+bash -x bin/git-archive-all.sh --prefix ceph-$version/ \
 		       --verbose \
 		       --ignore corpus \
 		       $outfile.tar
@@ -181,14 +213,17 @@ tar cvf $outfile.version.tar $outfile/src/.git_version $outfile/ceph.spec
 # at the three URLs referenced below (may involve uploading to download.ceph.com)
 boost_version=1.75.0
 download_boost $boost_version 953db31e016db7bb207f11432bef7df100516eeb746843fa0486a222e3fd49cb \
+               $LOCAL_FILE_SERVER \
                https://boostorg.jfrog.io/artifactory/main/release/$boost_version/source \
                https://downloads.sourceforge.net/project/boost/boost/$boost_version \
                https://download.ceph.com/qa
 download_liburing 0.7 8e2842cfe947f3a443af301bdd6d034455536c38a455c7a700d0c1ad165a7543 \
+                  $LOCAL_FILE_SERVER \
                   https://github.com/axboe/liburing/archive \
                   https://git.kernel.dk/cgit/liburing/snapshot
 pmdk_version=1.10
 download_pmdk $pmdk_version 08dafcf94db5ac13fac9139c92225d9aa5f3724ea74beee4e6ca19a01a2eb20c \
+               $LOCAL_FILE_SERVER \
                https://github.com/pmem/pmdk/releases/download/$pmdk_version
 build_dashboard_frontend
 generate_rook_ceph_client
